name: Sakurazaka46 Blog Checker

on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install requests beautifulsoup4

    - name: Run script
      run: python blog_checker.py
      env:
        WEBHOOK_ENDO_H: ${{ secrets.WEBHOOK_ENDO_H }}
        WEBHOOK_OZONO: ${{ secrets.WEBHOOK_OZONO }}
        WEBHOOK_ONUMA: ${{ secrets.WEBHOOK_ONUMA }}
        WEBHOOK_KOUSAKA: ${{ secrets.WEBHOOK_KOUSAKA }}
        WEBHOOK_TAMURA: ${{ secrets.secrets.WEBHOOK_TAMURA }}
        WEBHOOK_FUJIYOSHI: ${{ secrets.WEBHOOK_FUJIYOSHI }}
        WEBHOOK_MASUMOTO: ${{ secrets.WEBHOOK_MASUMOTO }}
        WEBHOOK_MATSUDA: ${{ secrets.WEBHOOK_MATSUDA }}
        WEBHOOK_MORITA: ${{ secrets.WEBHOOK_MORITA }}
        WEBHOOK_MORIYA: ${{ secrets.WEBHOOK_MORIYA }}
        WEBHOOK_YAMASAKI: ${{ secrets.WEBHOOK_YAMASAKI }}
        WEBHOOK_ISHIMORI: ${{ secrets.WEBHOOK_ISHIMORI }}
        WEBHOOK_ENDO_R: ${{ secrets.WEBHOOK_ENDO_R }}
        WEBHOOK_ODAKURA: ${{ secrets.WEBHOOK_ODAKURA }}
        WEBHOOK_KOJIMA: ${{ secrets.WEBHOOK_KOJIMA }}
        WEBHOOK_TANIGUCHI: ${{ secrets.WEBHOOK_TANIGUCHI }}
        WEBHOOK_NAKAJIMA: ${{ secrets.WEBHOOK_NAKAJIMA }}
        WEBHOOK_MATONO: ${{ secrets.WEBHOOK_MATONO }}
        WEBHOOK_MUKAI: ${{ secrets.WEBHOOK_MUKAI }}
        WEBHOOK_MURAI: ${{ secrets.WEBHOOK_MURAI }}
        WEBHOOK_MURAYAMA: ${{ secrets.WEBHOOK_MURAYAMA }}
        WEBHOOK_YAMASHITA: ${{ secrets.WEBHOOK_YAMASHITA }}
        WEBHOOK_ASAI: ${{ secrets.WEBHOOK_ASAI }}
        WEBHOOK_INAGUMA: ${{ secrets.WEBHOOK_INAGUMA }}
        WEBHOOK_KATUMATA: ${{ secrets.WEBHOOK_KATUMATA }}
        WEBHOOK_SATO: ${{ secrets.WEBHOOK_SATO }}
        WEBHOOK_NAKAGAWA: ${{ secrets.WEBHOOK_NAKAGAWA }}
        WEBHOOK_MATSUMOTO: ${{ secrets.WEBHOOK_MATSUMOTO }}
        WEBHOOK_MEGURO: ${{ secrets.WEBHOOK_MEGURO }}
        WEBHOOK_YAMAKAWA: ${{ secrets.WEBHOOK_YAMAKAWA }}
        WEBHOOK_YAMADA: ${{ secrets.WEBHOOK_YAMADA }}

      - name: Run Insta Check
        env:
          WEBHOOK_TEN: ${{ secrets.WEBHOOK_TEN }}
          WEBHOOK_AIRI: ${{ secrets.WEBHOOK_AIRI }}
        run: python insta_check.py

      - name: Commit and push changes (Cache)
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add last_blogs.json || true
          git add insta_history.json || true
          git commit -m "Update cache [skip ci]" || true
          git push || true

