MEMBERS = [
    {
        "username": "yamasaki.ten",
        "webhook_env": "WEBHOOK_TEN",
    },
    {
        "username": "airi.taniguchi.official",
        "webhook_env": "WEBHOOK_AIRI",
    },
    {
        "username": "rina_ino_",
        "webhook_env": "WEBHOOK_RINA_I",
    },
    {
        "username": "endohikari_official",
        "webhook_env": "WEBHOOK_HIKARI",
    },
    {
        "username": "ozonoreis2",
        "webhook_env": "WEBHOOK_REI",
    },
    {
        "username": "akiho_onuma_official",
        "webhook_env": "WEBHOOK_AKIHO",
    },
    {
        "username": "seki_yumiko_official",
        "webhook_env": "WEBHOOK_YUMIKO",
    },
    {
        "username": "takemotoyui_official",
        "webhook_env": "WEBHOOK_YUI",
    },
    {
        "username": "tamura.hono.official",
        "webhook_env": "WEBHOOK_HONO",
    },
    {
        "username": "fujiyoshi.karin",
        "webhook_env": "WEBHOOK_KARIN",
    },
    {
        "username": "matsudarina_official",
        "webhook_env": "WEBHOOK_RINA_M",
    },
    {
        "username": "rena_moriya_official",
        "webhook_env": "WEBHOOK_RENA",
    },
    {
        "username": "rika.ishimori.official",
        "webhook_env": "WEBHOOK_RIKA",
    },
    {
        "username": "riko.endo_official",
        "webhook_env": "WEBHOOK_RIKO",
    },
    {
        "username": "reinaodakura_official",
        "webhook_env": "WEBHOOK_REINA_O",
    },
    {
        "username": "yuzuki_nakashima_official",
        "webhook_env": "WEBHOOK_YUZUKI",
    },
    {
        "username": "yu.murai_official",
        "webhook_env": "WEBHOOK_YU",
    },
    {
        "username": "miumurayama_official",
        "webhook_env": "WEBHOOK_MIU",
    },
    {
        "username": "miichan_official",
        "webhook_env": "WEBHOOK_MATONO",
    },
    {
        "username": "yuuka_sugai_official",
        "webhook_env": "WEBHOOK_YUUKA",
    },
]
